# Generated by Django 3.0.3 on 2020-05-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='talles',
        ),
    ]
