# Generated by Django 3.0.3 on 2020-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_talles'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talles',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=3),
        ),
    ]
