# Generated by Django 3.0.3 on 2020-05-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_talles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talles',
            field=models.CharField(max_length=3),
        ),
    ]
