# Generated by Django 3.0.3 on 2020-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20200521_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('C', 'Carteras'), ('Z', 'Zapatos'), ('J', 'Jeans'), ('ZA', 'Zapatillas')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/$D/'),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
