# Generated by Django 3.0.3 on 2020-05-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20200521_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
