# Generated by Django 3.0.3 on 2020-05-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
