# Generated by Django 3.0.3 on 2020-05-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20200521_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristica1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristica2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristica3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristica4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
