# Generated by Django 3.0.3 on 2020-05-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_auto_20200524_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
