# Generated by Django 3.0.3 on 2020-05-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_auto_20200524_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='A1.png', upload_to=''),
        ),
    ]
